### ISSUE TITLE
Retrying timed out requests leads to retry storms

### ISSUE THREAD

**Issue by jonsyu1** [palantir/conjure-java-runtime#1084]
## What happened?
An expensive request that always times out was retried at multiple levels of the stack, causing a retry storm.

For example, the client makes an expensive request that goes through services `A -> B -> C`. `A` times out and retries the request 3 times. Each attempt causes `B` to time out and retry its request to `C` 3 times.

```
Caused by: java.net.SocketTimeoutException: {throwable3_message}
	at okio.Okio$4.newTimeoutException(Okio.java:232)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:226)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:202)
```
## What did you want to happen?
Do not retry requests that time out. Retrying on other `IOException`s is still desirable because it eventually produces a `SafeIoException` that results in a 500. Timeout failures are different because the caller will time out before the callee can produce a 500. We do not want to set the retry count to 0 because we still want other `IOException`s to be retried.

**Comment by pkoenig10** [comment]
Related issue about not retrying non-idempotent requests that timeout: #897

**Comment by iamdanfox** [comment]
Closing out because we landed https://github.com/palantir/conjure-java-runtime/pull/1085
