### ISSUE TITLE
NPE in RemotingOkHttpCall.shouldRetry

### ISSUE THREAD

**Issue by raiju** [palantir/conjure-java-runtime#1165]
## What happened?

Error bubbled up to root:
```
java.lang.NullPointerException:
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall.shouldRetry(RemotingOkHttpCall.java:284)
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall.access$300(RemotingOkHttpCall.java:60)
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall$3.onFailure(RemotingOkHttpCall.java:196)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:225)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.palantir.tracing.DeferredTracer.withTrace(DeferredTracer.java:115)
	at com.palantir.tracing.Tracers$TracingAwareCallable.call(Tracers.java:356)
	at com.palantir.tracing.WrappingExecutorService.lambda$wrapTask$0(WrappingExecutorService.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Version: com.palantir.conjure.java.runtime:okhttp-clients:4.31.4
LOC: https://github.com/palantir/conjure-java-runtime/blob/4.31.4/okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java#L284

This must be `socketTimeout.getMessage()` returning `null`.

## What did you want to happen?

No NPE is thrown

**Comment by raiju** [comment]
@iamdanfox As far as I can tell, the `SocketTimeoutException` is constructed by `OkHttp`. Happy to contribute a fix (either here or upstream), just not entirely sure what the expected behavior is in this case. Do we assume a null message ~> not a connect timeout?
