### ISSUE TITLE
SerializableErrorToExceptionConverter doesn't handle javax.ws.rs.NotAllowedException

### ISSUE THREAD

**Issue by ash211** [palantir/conjure-java-runtime#128]
```
    java.lang.RuntimeException: Failed to construct exception as class javax.ws.rs.NotAllowedException, constructing RuntimeException instead: java.lang.NoSuchMethodException: javax.ws.rs.NotAllowedException.<init>(java.lang.String)
    HTTP 405 Method Not Allowed
        at com.palantir.remoting.http.errors.SerializableErrorToExceptionConverter.getException(SerializableErrorToExceptionConverter.java:82) ~[error-handling-0.11.0.jar:na]
        at com.palantir.remoting.http.errors.FeignSerializableErrorErrorDecoder.decode(FeignSerializableErrorErrorDecoder.java:43) ~[http-clients-0.11.0.jar:na]
        at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:126) ~[feign-core-8.16.0.jar:8.16.0]
        at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:74) ~[feign-core-8.16.0.jar:8.16.0]
        at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-8.16.0.jar:8.16.0]
        at com.sun.proxy.$Proxy57.createDataset(Unknown Source) ~[na:na]
```

I think the problem is that https://github.com/palantir/http-remoting/blob/0072e03b3e95b4b666b1b2b841ba4c08092e806c/error-handling/src/main/java/com/palantir/remoting/http/errors/SerializableErrorToExceptionConverter.java#L137 is looking for a constructor with one (String) parameter, or a constructor with (String, Throwable) parameters.

But `NotAllowedException` has a final variadic parameter at the end:

`public NotAllowedException(String allowed, String... moreAllowed) {`

`public NotAllowedException(String message, Throwable cause, String... allowedMethods) {`

**Comment by markelliot** [comment]
What version of Jersey are you trying to use?

**Comment by ash211** [comment]
I believe it's 2.22.1

`NotAllowedException` is coming from `javax.ws.rs-api-2.0.1-sources.jar` and `JerseyClient` is coming from `jersey-client-2.22.1-sources.jar`

**Comment by uschi2000** [comment]
I believe this is solved.

**Comment by uschi2000** [comment]
(because we no longer re-create the original exceptions)
