### ISSUE TITLE
okhttp-clients leaks response bodies when calls are interrupted

### ISSUE THREAD

**Issue by tjwilson90** [palantir/conjure-java-runtime#1385]
The `PaxosQuorumChecker` in atlasdb makes remote calls to multiple remote `PaxosAcceptor.getLatestSequencePreparedOrAccepted` endpoints, waits for a quorum of them to respond, then attempts to cancel the remainder. This appears to result in a leak of an okhttp3 `ResponseBody`
```
A connection to <REDACTED> was leaked. Did you forget to close a response body?
	at okhttp3.internal.platform.Platform.getStackTraceForCloseable(Platform.java:149)
	at okhttp3.RealCall.captureCallStackTrace(RealCall.java:116)
	at okhttp3.RealCall.enqueue(RealCall.java:125)
	at com.palantir.conjure.java.okhttp.ForwardingCall.enqueue(ForwardingCall.java:48)
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall.enqueueInternal(RemotingOkHttpCall.java:217)
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall.enqueueClosingEntireSpan(RemotingOkHttpCall.java:201)
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall.access$100(RemotingOkHttpCall.java:59)
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall$2.onSuccess(RemotingOkHttpCall.java:187)
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall$2.onSuccess(RemotingOkHttpCall.java:181)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1021)
	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.common.util.concurrent.ImmediateFuture.addListener(ImmediateFuture.java:38)
	at com.google.common.util.concurrent.Futures.addCallback(Futures.java:996)
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall.enqueue(RemotingOkHttpCall.java:181)
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall.execute(RemotingOkHttpCall.java:114)
	at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:160)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:98)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:77)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:102)
	at com.sun.proxy.$Proxy83.getLatestSequencePreparedOrAccepted(Unknown Source)
	at com.palantir.tritium.proxy.InstrumentedPaxosAcceptor$4.getLatestSequencePreparedOrAccepted(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.palantir.common.proxy.ExperimentRunningProxy.handleInvocation(ExperimentRunningProxy.java:91)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:86)
	at com.sun.proxy.$Proxy83.getLatestSequencePreparedOrAccepted(Unknown Source)
	at com.palantir.paxos.SingleLeaderAcceptorNetworkClient.lambda$getLatestSequencePreparedOrAccepted$2(SingleLeaderAcceptorNetworkClient.java:64)
	at com.palantir.paxos.PaxosQuorumChecker.lambda$collectResponses$4(PaxosQuorumChecker.java:196)
	at com.palantir.common.concurrent.MultiplexingCompletionService.lambda$submitAndPrepareForQueueing$0(MultiplexingCompletionService.java:88)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.codahale.metrics.InstrumentedExecutorService$InstrumentedRunnable.run(InstrumentedExecutorService.java:176)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.palantir.common.concurrent.PTExecutors.lambda$wrapRunnable$1(PTExecutors.java:602)
	at com.palantir.tracing.Tracers$TracingAwareRunnable.run(Tracers.java:492)
	at com.palantir.common.concurrent.ForwardingRunnableFuture.run(ForwardingRunnableFuture.java:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
The call in atlasdb appears to swallow any actual error produced by the remote call itself, so I'm not sure how the response body is actually being leaked.

I made an attempt to reproduce this in a simple test that simply made remote requests in a loop and cancelled them, but was unable to reproduce this error. Instead, I got a different error logged
```
com.palantir.conjure.java.okhttp.LeakDetector: Resource leak detected - did you forget to close a resource properly? This will likely hurt performance. Stack trace is of the call where the acquire happened. (resourceType: com.netflix.concurrency.limits.Limiter$Listener)
com.palantir.logsafe.exceptions.SafeRuntimeException: Runtime exception for stack trace
	at com.palantir.conjure.java.okhttp.LeakDetector.maybeCreateStackTrace(LeakDetector.java:38)
	at com.palantir.conjure.java.okhttp.ConcurrencyLimiters$DefaultConcurrencyLimiter.acquire(ConcurrencyLimiters.java:231)
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall.enqueue(RemotingOkHttpCall.java:179)
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall.execute(RemotingOkHttpCall.java:114)
	at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:160)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:98)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:77)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:102)
```
along with this error from the remote call
```
feign.RetryableException: Call cancelled via interruption executing GET <REDACTED>
	at feign.FeignException.errorExecuting(FeignException.java:65)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:105)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:77)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:102)
	at com.sun.proxy.$Proxy25.getVersion(Unknown Source)
Caused by: java.io.InterruptedIOException: Call cancelled via interruption
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall.execute(RemotingOkHttpCall.java:138)
	at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:160)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:98)
	... 8 more
```

**Comment by clockfort** [comment]
@iamdanfox do you have any thoughts here? this issue is really clogging up our logs ( https://pg-jira.palantir.tech/browse/PG-142254 ) and I'd like to get it fixed before our next major release.

**Comment by clockfort** [comment]
@iamdanfox do you have any thoughts here? this issue is really clogging up our logs and I'd like to get it fixed before our next major release.

**Comment by carterkozak** [comment]
@tjwilson90 @clockfort Can you give this a shot with [4.49.0](https://github.com/palantir/conjure-java-runtime/releases/tag/4.49.0) which includes https://github.com/palantir/conjure-java-runtime/pull/1391? It adds a bit of safety that could resolve the issue and also provides more diagnostic information when things go sideways.

**Comment by tjwilson90** [comment]
I'll try this later today.
