### ISSUE TITLE
If jaxrs server can't parse request, it sends an error that SerializableErrorToExceptionConverter cannot convert to SerializableError

### ISSUE THREAD

**Issue by justinuang** [palantir/conjure-java-runtime#220]
```
ERROR [2016-08-26 17:59:19,051] com.palantir.remoting1.errors.SerializableErrorToExceptionConverter: Error 400. Reason: Bad Request. Failed to parse error body and instantiate ex
 at [Source: {"code":400,"message":"Unable to process JSON"}; line: 1, column: 12] (through reference chain: com.palantir.remoting1.errors.Json["code"]). Body:
{"code":400,"message":"Unable to process JSON"}
! com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "code" (class com.palantir.remoting1.errors.ImmutableSerializableError$Json), not marked as
!  at [Source: {"code":400,"message":"Unable to process JSON"}; line: 1, column: 12] (through reference chain: com.palantir.remoting1.errors.Json["code"])
! at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:839) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1045) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1352) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1330) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:264) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:161) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1095) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726) ~[jackson-databind-2.6.3.jar:2.6.3]
! at com.palantir.remoting1.errors.SerializableErrorToExceptionConverter.getException(SerializableErrorToExceptionConverter.java:60) ~[error-handling-1.0.0-alpha4.jar:na]
! at com.palantir.remoting1.jaxrs.feignimpl.FeignSerializableErrorErrorDecoder.decode(FeignSerializableErrorErrorDecoder.java:45) [jaxrs-clients-1.0.0-alpha4.jar:na]
! at httpremoting.shaded.feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:134) [jaxrs-clients-1.0.0-alpha4.jar:na]
! at httpremoting.shaded.feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76) [jaxrs-clients-1.0.0-alpha4.jar:na]
! at httpremoting.shaded.feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) [jaxrs-clients-1.0.0-alpha4.jar:na]
! at com.sun.proxy.$Proxy51.submitModule(Unknown Source) [na:na]
... CALLING CODE ...
```

**Comment by justinuang** [comment]
This happened when I accidentally changed the API that the client was using without upgrading the server.
