### ISSUE TITLE
Using incorrect URI throws a NoSuchMethodError

### ISSUE THREAD

**Issue by szunami** [palantir/conjure-java-runtime#273]
I included a typo in my URI and was greeted with the following Exception:

java.lang.NoSuchMethodError: com.palantir.remoting.http.errors.SerializableErrorToExceptionConverter.getException(Ljava/util/Collection;ILjava/lang/String;Ljava/io/InputStream;)Ljava/lang/RuntimeException;
at com.palantir.remoting.http.errors.FeignSerializableErrorErrorDecoder.decode(FeignSerializableErrorErrorDecoder.java:45)
    at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:134)
    at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
    at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
    at com.sun.proxy.$Proxy18.getResourceByPath(Unknown Source)

This didn't help me debug very much.

**Comment by uschi2000** [comment]
This is almost certainly a version mismatch. Can you check that error-handling and jaxrs-clients have the same version?

**Comment by uschi2000** [comment]
closing for now.

**Comment by uschi2000** [comment]
let me know if this is still an issue.
