### ISSUE TITLE
Add trustStorePassword to the SSLConfiguration

### ISSUE THREAD

**Issue by hsaraogi** [palantir/conjure-java-runtime#312]
The SSLConfiguration misses the trustStorePassword. I hit an error when trying to use Atomix with the security configured from SSLConfiguration.

```
 INFO  [2017-01-03 12:45:46,090] io.atomix.catalyst.transport.netty.NettyClient: Connecting to localhost/127.0.0.1:8700
WARN  [2017-01-03 12:45:46,092] io.netty.channel.ChannelInitializer: Failed to initialize a channel. Closing: [id: 0xb56ffa11]
! java.lang.NullPointerException: null
! at io.atomix.catalyst.transport.netty.NettyTls.loadKeystore(NettyTls.java:90) ~[catalyst-netty-1.1.1.jar:na]
! at io.atomix.catalyst.transport.netty.NettyTls.initSslEngine(NettyTls.java:59) ~[catalyst-netty-1.1.1.jar:na]
! at io.atomix.catalyst.transport.netty.NettyClient$1.initChannel(NettyClient.java:76) ~[catalyst-netty-1.1.1.jar:na]
! at io.atomix.catalyst.transport.netty.NettyClient$1.initChannel(NettyClient.java:71) ~[catalyst-netty-1.1.1.jar:na]
! at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:143) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:129) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:733) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:450) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:378) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:424) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) [netty-common-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-common-4.0.33.Final.jar:4.0.33.Final]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
WARN  [2017-01-03 12:45:46,871] io.netty.channel.ChannelInitializer: Failed to initialize a channel. Closing: [id: 0x95e57e26, /172.18.0.3:57064 => /172.18.0.3:8443]
! java.lang.NullPointerException: null
! at io.atomix.catalyst.transport.netty.NettyTls.loadKeystore(NettyTls.java:90) ~[catalyst-netty-1.1.1.jar:na]
! at io.atomix.catalyst.transport.netty.NettyTls.initSslEngine(NettyTls.java:59) ~[catalyst-netty-1.1.1.jar:na]
! at io.atomix.catalyst.transport.netty.NettyServer$1.initChannel(NettyServer.java:101) ~[catalyst-netty-1.1.1.jar:na]
! at io.atomix.catalyst.transport.netty.NettyServer$1.initChannel(NettyServer.java:96) ~[catalyst-netty-1.1.1.jar:na]
! at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:68) ~[netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:143) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:129) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:733) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:450) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:378) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:424) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) [netty-common-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-transport-4.0.33.Final.jar:4.0.33.Final]
! at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-common-4.0.33.Final.jar:4.0.33.Final]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
```

Is there a reason that the SSL config misses the truststore password?

**Comment by markelliot** [comment]
Java KeyStores containing just certificates (ie a trust store) may always be read without providing a password, so we omit it. 

If you're trying to initialize a keystore (I'm not super familiar with Netty), and you need an actual key, you will have to provide the password -- that config is optional, but already available.

**Comment by hsaraogi** [comment]
Atomix Netty uses the same logic to load both the trustStore and the keyStore:

From NettyTls.java:
```
        if(this.properties.sslTrustStorePath() != null) {
            LOGGER.debug("Using separate trust store");
            trustStore = this.loadKeystore(this.properties.sslTrustStorePath(), this.properties.sslTrustStorePassword());
        } else {
            trustStore = keyStore;
            LOGGER.debug("Using key store as trust store");
        }
```

```
    private KeyStore loadKeystore(String path, String password) throws Exception {
        Assert.notNull(path, "Path");
        File file = new File(path);
        LOGGER.debug("Using JKS at {}", file.getCanonicalPath());
        KeyStore ks = KeyStore.getInstance("JKS");
        ks.load(new FileInputStream(file.getCanonicalPath()), password.toCharArray());
        return ks;
    }
```

I can modify my config to have an Optional trustStore password. But shouldn't an SSLConfig have it because some truststores might need the password?

**Comment by markelliot** [comment]
No trust stores require a password. You should fill out the keystore block in addition to the trust store block (fine if they reference the same file), and pass Netty a valid keystore.

**Comment by markelliot** [comment]
in particular, since you're looking to load a keystore, use this part of the SslConfiguration: https://github.com/palantir/http-remoting/blob/develop/ssl-config/src/main/java/com/palantir/remoting1/config/ssl/SslConfiguration.java#L50-L52

**Comment by hsaraogi** [comment]
Not sure to understand clearly, Atomix loads both the trustStore and the keyStore with ``loadKeyStore``. It uses the property ``trustStorePassword`` when loading the trustStore. 

```            
trustStore = this.loadKeystore(this.properties.sslTrustStorePath(), this.properties.sslTrustStorePassword());
```
Currently, the ``trustStorePath`` is configured from Skylab (It is a required parameter in the SslConfiguration) but the config does not have any trustStorePassword and the property is not passed to Atomix(Netty) [resulting in NullPointerException]. Will passing ``keyStorePassword`` as the ``trustStorePassword`` to Atomix work? i.e. are the two passwords interchangeable?

**Comment by markelliot** [comment]
unfortunately it sounds like there's a bug in Atomix, you could submit a patch to https://github.com/atomix/catalyst/blob/master/netty/src/main/java/io/atomix/catalyst/transport/netty/NettyTls.java#L90 which checks to see if password is null, and if so passes null (a valid value to to KeyStore#load, otherwise converts to a charArray as is.

**Comment by markelliot** [comment]
obviously if your truststore and your keystore are the same file and have the same password (and you want to make guarantees about that), you can pass any valid password in here.

we're not going to modify SslConfiguration to take a trustStorePassword, per above, it's _never_ required.

**Comment by hsaraogi** [comment]
Agreed, it seems like an Atomix issue, will find a temporary workaround and submit a PR to Atomix. Thanks :)
