### ISSUE TITLE
[Needs Investigation] Returning an Optional<String> when Content-Type=application/json causes unexpected errors

### ISSUE THREAD

**Issue by leeavital** [palantir/conjure-java-runtime#32]
```
Exception in thread "main" feign.FeignException: Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)
 at [Source: java.io.BufferedReader@2b662a77; line: 1, column: 2] reading GET http://localhost:8442/.....
    at feign.FeignException.errorReading(FeignException.java:48)
    at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:127)
    at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71)
    at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
    at com.sun.proxy.$Proxy19.getPath(Unknown Source)
```

This was a problem in 0.3.0 and is still a problem in 0.4.0.

**Comment by markelliot** [comment]
Any chance you could document a minimal example that reliably reproduces the problem? (Or...contribute that as a test?)

**Comment by nmiyake** [comment]
I tried this out for GET requests, and I do get exceptions when return type is annotated with `@Produces(MediaType.APPLICATION_JSON)` rather than `@Produces(MediaType.TEXT_PLAIN)` if the method is returning either `String` or `Optional<String>`. However, exception I get is different:

```
feign.FeignException: Unrecognized token 'foo': was expecting 'null', 'true', 'false' or NaN
 at [Source: java.io.BufferedReader@146d984e; line: 1, column: 7] reading GET http://localhost:61992/optionalStringJson
    at feign.FeignException.errorReading(FeignException.java:48)
    at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:127)
    at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:71)
    at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:94)
    at com.sun.proxy.$Proxy59.getOptionalStringJson(Unknown Source)
    at feign.OptionalAwareDecoderTest.testOptionalStringJson(OptionalAwareDecoderTest.java:87)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'foo': was expecting 'null', 'true', 'false' or NaN
 at [Source: java.io.BufferedReader@146d984e; line: 1, column: 7]
    at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2462)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2439)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchToken(ReaderBasedJsonParser.java:2291)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._matchFalse(ReaderBasedJsonParser.java:2258)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:661)
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3742)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3687)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2775)
    at feign.jackson.JacksonDecoder.decode(JacksonDecoder.java:65)
    at feign.TextDelegateDecoder.decode(TextDelegateDecoder.java:53)
    at feign.InputStreamDelegateDecoder.decode(InputStreamDelegateDecoder.java:41)
    at feign.OptionalAwareDecoder.decode(OptionalAwareDecoder.java:45)
    at feign.SynchronousMethodHandler.decode(SynchronousMethodHandler.java:146)
    at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:118)
    ... 32 more
```

This may also be expected behavior (I don't fully understand how that annotation is expected to be processed).

I've pushed a PR to illustrate the point (#64) -- it contains tests that demonstrate the failure that I encountered (although this "failure" behavior may actually be correct).

@leeavital , does this sound like the same issue, or are you referring to something else? If it's something else, can you provide a specific example?

**Comment by nmiyake** [comment]
@leeavital ping?

**Comment by leeavital** [comment]
I think that they're the in the same family of errors. The problem may be that we're not serializing correctly -- not that we're not deserializaing correctly. 

In my case, I got `/a/path` instead of `"/a/path"`

In your case you got `foo` instead of `"foo"`

**Comment by markelliot** [comment]
this is the same as #131, closing for the same reason
