### ISSUE TITLE
Be more resilient to Http2Agent installation failures

### ISSUE THREAD

**Issue by ash211** [palantir/conjure-java-runtime#403]
Saw this stacktrace when running in docker container `alpine-java:8u121-t95` with the Oracle JDK:

```
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:244)
    at com.ea.agentloader.AgentLoader.loadAgent(AgentLoader.java:77)
    at com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:148)
    at com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:102)
    at com.palantir.remoting2.http2.Http2Agent.install(Http2Agent.java:26)
    at com.palantir.remoting2.jaxrs.FeignJaxRsClientBuilder.<clinit>(FeignJaxRsClientBuilder.java:65)
    ... 48 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:240)
    ... 53 more
Caused by: java.lang.RuntimeException: Can't attach to this jvm. Add -javaagent:/tmp/javaagent.com.palantir.remoting2.http2.Http2Agent9090971280470105146.jar to the commandline
    at com.ea.agentloader.AgentLoaderHotSpot.loadAgent(AgentLoaderHotSpot.java:74)
    ... 58 more
Caused by: com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
    at sun.tools.attach.HotSpotVirtualMachine.loadAgent(HotSpotVirtualMachine.java:121)
    at com.ea.agentloader.AgentLoaderHotSpot.loadAgent(AgentLoaderHotSpot.java:65)
    ... 58 more
```

and saw this exception when running in docker container `openjdk:8-alpine` with the OpenJDK:

```
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:244)
    at com.ea.agentloader.AgentLoader.loadAgent(AgentLoader.java:77)
    at com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:148)
    at com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:102)
    at com.palantir.remoting2.http2.Http2Agent.install(Http2Agent.java:26)
    at com.palantir.remoting2.jaxrs.FeignJaxRsClientBuilder.<clinit>(FeignJaxRsClientBuilder.java:65)
    ... 48 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:240)
    ... 53 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at com.ea.agentloader.AgentLoaderHotSpot.getVirtualMachine(AgentLoaderHotSpot.java:113)
    at com.ea.agentloader.AgentLoaderHotSpot.loadAgent(AgentLoaderHotSpot.java:56)
    ... 58 more
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at com.ea.agentloader.AgentLoaderHotSpot.getVirtualMachine(AgentLoaderHotSpot.java:104)
    ... 59 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: Unable to get pid of LinuxThreads manager thread
    at sun.tools.attach.LinuxVirtualMachine.<init>(LinuxVirtualMachine.java:86)
    ... 64 more
```

To fix I would propose:
1) for the short term, put a try/catch around https://github.com/palantir/http-remoting/blob/develop/http2-agent/src/main/java/com/palantir/remoting2/http2/Http2Agent.java#L28 to be more resilient to installation failures
2) more deeply investigate the failures and attempt to fix in whichever upstream project that has this bug (ea-agent-loader, JDK, jetty-alpn-agent)

**Comment by markelliot** [comment]
Yeah, quick fix seems fine.
