### ISSUE TITLE
UriSelectorImpl fails to redirect unless (current url) isPathPrefixFor (redirectBaseUrl)

### ISSUE THREAD

**Issue by dansanduleac** [palantir/conjure-java-runtime#619]
Which can lead to errors like:
```
Caused by: java.io.IOException: Failed to determine suitable target URL for request URL https://localhost:15002/base-1/some/path amongst known base URLs: [https://localhost:15003/base-2, https://localhost:15002/base-1]
        at com.palantir.remoting3.okhttp.CurrentUrlInterceptor.lambda$intercept$0(CurrentUrlInterceptor.java:42)
        at java.util.Optional.orElseThrow(Optional.java:290)
        at com.palantir.remoting3.okhttp.CurrentUrlInterceptor.intercept(CurrentUrlInterceptor.java:40)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.palantir.remoting3.okhttp.QosRetryLaterInterceptor.intercept(QosRetryLaterInterceptor.java:44)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall.execute(RealCall.java:69)
        ...
```

**Comment by dansanduleac** [comment]
It looks like this  is happening because the path of the url it tries to redirect to, `/base-2`, is not a prefix of the current requested url's path which is `/base-1/some/path`.
I wonder why we impose this restriction, meaning we only need to swap out the host & port, when we could just as well replace the path's prefix.
