### ISSUE TITLE
Support for non-http-remoting generated 503/504/429/etc

### ISSUE THREAD

**Issue by jared2501** [palantir/conjure-java-runtime#631]
The envoy proxy does not currently support specifying the response body that it returns in it's errors (although there is an FR tracking it: https://github.com/envoyproxy/envoy/issues/1178).

In the meantime, it probably makes sense to not just turn 503/504/etc errors that don't conform to SerializableError into RuntimeExceptions. I.e. currently you get this:

```
java.lang.RuntimeException: Error 504. Body:
upstream request timeout

	at com.palantir.remoting3.errors.SerializableErrorToExceptionConverter.getException(SerializableErrorToExceptionConverter.java:69)
	at com.palantir.remoting3.okhttp.SerializableErrorInterceptor.intercept(SerializableErrorInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
```

**Comment by jared2501** [comment]
@uschi2000

**Comment by uschi2000** [comment]
Agree. Should be must simpler to do this now, see https://github.com/palantir/http-remoting/blob/develop/okhttp-clients/src/main/java/com/palantir/remoting3/okhttp/RemotingOkHttpCall.java#L162

**Comment by markelliot** [comment]
What will 503s be turned into if not RuntimeExceptions?

**Comment by jared2501** [comment]
Whatever 503's are turned into now? Looking at the code in the stacktrace it appears to be a SerializableError.

**Comment by iamdanfox** [comment]
@gregakinman @cbrockington do you want this to stay open as part of the mesh work you guys are doing?

**Comment by cbrockington** [comment]
Leave it closed for now. I can reopen if it is a problem.  Thanks.
