### ISSUE TITLE
In-compatible with latest java version 1.8_161

### ISSUE THREAD

**Issue by hsaraogi** [palantir/conjure-java-runtime#679]
```
Exception in thread "OkHttp Dispatcher" java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension
        at sun.security.ssl.ClientHandshaker.getKickstartMessage(ClientHandshaker.java:1438)
        at sun.security.ssl.Handshaker.kickstart(Handshaker.java:1087)
        at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1497)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1361)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.palantir.remoting3.okhttp.UserAgentInterceptor.intercept(UserAgentInterceptor.java:44)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.palantir.remoting3.tracing.okhttp3.OkhttpTraceInterceptor.intercept(OkhttpTraceInterceptor.java:57)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.palantir.remoting3.okhttp.MultiServerRetryInterceptor.intercept(MultiServerRetryInterceptor.java:48)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.palantir.remoting3.okhttp.QosRetryOtherInterceptor.intercept(QosRetryOtherInterceptor.java:50)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.palantir.remoting3.okhttp.CurrentUrlInterceptor.intercept(CurrentUrlInterceptor.java:49)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.palantir.remoting3.okhttp.QosRetryLaterInterceptor.intercept(QosRetryLaterInterceptor.java:44)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.palantir.remoting3.okhttp.SerializableErrorInterceptor.intercept(SerializableErrorInterceptor.java:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at com.palantir.remoting3.tracing.DeferredTracer.withTrace(DeferredTracer.java:43)
        at com.palantir.remoting3.tracing.Tracers$TracingAwareCallable.call(Tracers.java:182)
        at com.palantir.remoting3.tracing.WrappingExecutorService.lambda$wrapTask$0(WrappingExecutorService.java:70)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

This is probably due to the alpn-boot version used as per https://github.com/alexa/alexa-avs-sample-app/issues/1093.

**Comment by uschi2000** [comment]
Should upgrade `org.mortbay.jetty.alpn:jetty-alpn-agent` to 2.0.7: https://github.com/jetty-project/jetty-alpn-agent/commit/1dd8bb233a0f4baa11dc7e40df5f1d45d1d176a0
