### ISSUE TITLE
JaxRsClient broken in 3.20.0

### ISSUE THREAD

**Issue by romnempire** [palantir/conjure-java-runtime#697]
on 3.20.0 - trying to create a JaxRsClient

fails with a:
```
java.lang.NoSuchMethodError: feign.okhttp.OkHttpClient.<init>(Lokhttp3/OkHttpClient;)V

	at com.palantir.remoting3.jaxrs.AbstractFeignJaxRsClientBuilder.build(AbstractFeignJaxRsClientBuilder.java:94)
	at com.palantir.remoting3.jaxrs.AbstractFeignJaxRsClientBuilder.build(AbstractFeignJaxRsClientBuilder.java:77)
	at com.palantir.remoting3.jaxrs.JaxRsClient.create(JaxRsClient.java:49)
	at com.palantir.remoting3.jaxrs.JaxRsClient.create(JaxRsClient.java:39)
	at (caller)
```

jumping into source from library, intellij claims AbstractFeignJaxRsClientBuilder.java:94 has a problem where OkHttpClient(com.squareup.okhttp.OkHttpClient) cannot be applied to okhttp3.OkHttpClient

possibly relevant dependencyInsight entries?

```
com.squareup.okhttp3:okhttp:3.9.0 (conflict resolution)
+--- com.palantir.remoting3:okhttp-clients:3.20.0
|    \--- com.palantir.remoting3:jaxrs-clients:3.20.0
|         \--- testCompile
+--- com.palantir.remoting3:tracing-okhttp3:3.20.0
|    +--- com.palantir.remoting3:jaxrs-clients:3.20.0 (*)
|    \--- com.palantir.remoting3:okhttp-clients:3.20.0 (*)
\--- com.squareup.okhttp3:logging-interceptor:3.9.0
     \--- com.palantir.remoting3:okhttp-clients:3.20.0 (*)

com.squareup.okhttp3:okhttp:3.2.0 -> 3.9.0
\--- com.netflix.feign:feign-okhttp:8.17.0
     +--- com.palantir.remoting3:jaxrs-clients:3.20.0
     |    \--- testCompile
     \--- com.palantir.remoting:http-clients:0.9.0

```

**Comment by uschi2000** [comment]
Can you show the output of `./gradlew dependencies`?

**Comment by romnempire** [comment]
old version of feign on classpath
