### ISSUE TITLE
Flaky com.palantir.remoting3.tracing.CloseableTracerTest

### ISSUE THREAD

**Issue by qinfchen** [palantir/conjure-java-runtime#731]
I have seen this test failure a few times in a pr that only has circle config changes:

https://circleci.com/gh/palantir/http-remoting/2132, 
https://circleci.com/gh/palantir/http-remoting/2124, 
https://circleci.com/gh/palantir/http-remoting/2123
```
startsAndClosesSpan - com.palantir.remoting3.tracing.CloseableTracerTest
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at com.palantir.remoting3.tracing.CloseableTracerTest.startsAndClosesSpan(CloseableTracerTest.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
```

**Comment by iamdanfox** [comment]
Another flake: https://circleci.com/gh/palantir/http-remoting/2170?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by qinfchen** [comment]
Publishing 3.38.0 failed twice because of this and 3.38.0 was release 9 days ago!
https://circleci.com/gh/palantir/http-remoting/2214
https://circleci.com/gh/palantir/http-remoting/2197

**Comment by qinfchen** [comment]
fixed by https://github.com/palantir/http-remoting/pull/773
