### ISSUE TITLE
Follow 3xx redirects

### ISSUE THREAD

**Issue by bmoylan** [palantir/conjure-java-runtime#735]
## What happened?

An exception was thrown for a 301 response with a valid `location` header:

```
Caused by: feign.RetryableException: Error 301. (Failed to parse response body as SerializableError.) Body:
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
 executing POST https://<URL>
	at feign.FeignException.errorExecuting(FeignException.java:67)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:102)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
```

## What did you want to happen?

Follow the redirect instead of throwing

**Comment by uschi2000** [comment]
http-remoting supports 308 for permanent redirect, but not 301. https://github.com/palantir/http-remoting#quality-of-service-retry-failover-throttling

**Comment by bmoylan** [comment]
OK luckily we control the server so we can change to 308. Is there an intentional reason that 301s are errors? It's a pretty common response code

**Comment by uschi2000** [comment]
http-remoting does intentionally not support all of HTTP. Codes with explicitly defined behavior are 308, 429, 503, see README.

**Comment by bmoylan** [comment]
Ack, understood
