### ISSUE TITLE
Error handler throws ClassNotFoundExceptions if not in a Jersey environment

### ISSUE THREAD

**Issue by j-baker** [palantir/conjure-java-runtime#85]
Was trying to use Gatekeeper in a non-Jersey environment (a test script), and instead of having errors decoded properly, received a bunch of ClassNotFoundExceptions (as in, if you are not in a jersey server, you cannot see any error messages).

This is probably because the exception decoded is not supposed to be used outside of a Jersey environment - see #24 for details.

I guess a reasonable solution would be to catch the ClassNotFoundException and use a RuntimeException to redo the whole shebang in that case?

```
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:189)
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
at java.util.stream.IntPipeline.forEach(IntPipeline.java:404)
at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:560)
at com.palantir.jbaker.PerfTest.main(perftest.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:152)
at javax.ws.rs.ext.RuntimeDelegate.getInstance(RuntimeDelegate.java:120)
at javax.ws.rs.core.Response$ResponseBuilder.newInstance(Response.java:848)
at javax.ws.rs.core.Response.status(Response.java:613)
at javax.ws.rs.WebApplicationException.<init>(WebApplicationException.java:226)
at com.palantir.remoting.http.errors.SerializableErrorErrorDecoder.constructException(SerializableErrorErrorDecoder.java:117)
at com.palantir.remoting.http.errors.SerializableErrorErrorDecoder.decode(SerializableErrorErrorDecoder.java:74)
at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:126)
at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:74)
at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:97)
at com.sun.proxy.$Proxy15.registerResource(Unknown Source)
at com.palantir.jbaker.PerfTest.lambda$main$2(perftest.java:42)
at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:205)
at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.internal.RuntimeDelegateImpl
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at javax.ws.rs.ext.FactoryFinder.newInstance(FactoryFinder.java:115)
at javax.ws.rs.ext.FactoryFinder.find(FactoryFinder.java:225)
at javax.ws.rs.ext.RuntimeDelegate.findDelegate(RuntimeDelegate.java:135)
... 21 more
```

**Comment by markelliot** [comment]
Could your test script depend on some JAX-RS exception implementations?

**Comment by j-baker** [comment]
It has the implementations - the difficulty is that the JAX-RS exceptions contain a Response, and to instantiate a Response you need an implementation of `RuntimeDelegate` on the classpath (it does classpath scanning to find the implementation).

So to create a JAX-RS exception, you need at least jersey-common on the classpath. Maybe it would be ok to just document this, or explain it in the error message? I don't think you can make http-clients depend on it, as I suspect that jersey 1 clients would have a sad time.

**Comment by markelliot** [comment]
That's fair, we should document.

I'm also open to having better ClassNotFound handling, our general production of Exceptions leaves a lot to be desired anyway.

**Comment by uschi2000** [comment]
fixed
