### ISSUE TITLE
com.palantir.conjure.java.serialization.CollectionValidationModule erroneously logs for empty Optionals

### ISSUE THREAD

**Issue by jroitgrund** [palantir/conjure-java-runtime#997]
## What happened?

With a `ObjectMappers.newServerObjectMapper()`, I tried to `convertToMap` a conjure generated object with an empty optional field. I tried both leaving the field out and explicitly setting it to `Optional.empty()`. In both cases, I got the following warning:

```
11:44:44.185 [main] WARN com.palantir.conjure.java.serialization.CollectionValidationModule - Detected a null value, null values are not allowed by Conjure
java.lang.IllegalArgumentException: null
	at com.palantir.conjure.java.serialization.CollectionValidationModule.onNull(CollectionValidationModule.java:150)
	at com.palantir.conjure.java.serialization.CollectionValidationModule.logIfNull(CollectionValidationModule.java:141)
	at com.palantir.conjure.java.serialization.CollectionValidationModule.access$000(CollectionValidationModule.java:49)
	at com.palantir.conjure.java.serialization.CollectionValidationModule$ValidatingHashMap.put(CollectionValidationModule.java:112)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:534)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3745)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3668)
```

## What did you want to happen?

No warnings for empty Optionals.

**Comment by jroitgrund** [comment]
Fixed by #996
